### ISSUE TITLE
Option to disable reveal animations

### ISSUE THREAD

**Issue by JensVanAssche** [rnosov/react-reveal#61]
I don't think this exists in the package yet: an option to disable reveal animations. And in extension: conditionally disable the animations (when the viewport is a certain size for example). This would be really helpful to disable the animations on mobile for example.

Thanks in advance!

**Comment by Fziliotti** [comment]
Anyone know some method to disable the animations using the react-reveal?

**Comment by YuriBrunetto** [comment]
Hey!

I also wanted to disable the animations on mobile. My workaround for this was to disable the animation directly in CSS, like so:

```css
/* disable react-reveal's animations */
.react-reveal {
  @media (max-width: 959px) {
    animation: none !important;
    opacity: 1 !important;
  }
}
```
