### ISSUE TITLE
Delay doesn't work with Custom CSS effects

### ISSUE THREAD

**Issue by cmdalbem** [rnosov/react-reveal#93]
When using a custom CSS effect with delay the element is rendered, normally, and after the delay the effect takes places.

React:
```javascript
<Reveal effect="blurIn" delay={500}>
    <img .../>
</Reveal>
```

CSS:
```css
@keyframes blurIn {
  from { 
    filter: blur(30px);
    opacity: 0.7;
  }
  
  to {
    filter: blur(0);
    opacity: 1;
  }
}
.blurIn {
  animation-name: blurIn;
}
```

## Result

![](http://g.recordit.co/ntsSq4IXxT.gif)
